3.6 (select): Format integer literal
When implementing the examples in my test repo,
clippy threw a fit because of formatting.
```
error: integer type suffix should be separated by an underscore
  --> src/main.rs:42:37
   |
42 |     let (value, set_value) = signal(0i32);
   |                                     ^^^^ help: add an underscore: `0_i32`
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unseparated_literal_suffix
   = note: requested on the command line with `-D clippy::unseparated-literal-suffix`
```

Either way, I find it more pretty when separated :3